import { chromium } from '@playwright/test';
const url = process.argv[2];
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium' });
const page = await browser.newPage();
page.on('console', (m) => console.log('CONSOLE', m.type(), m.text()));
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto(url, { waitUntil: 'networkidle' });
console.log('TITLE', await page.title());
console.log('BODY', (await page.locator('body').innerText()).slice(0, 400));
await browser.close();
